/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.devicepark.sdk.core.endpoint;

public final class Environment {
  public static final Environment DEFAULT = new Environment("https://dev-devicepark.testinium.io/management");

  private final String url;

  private Environment(String url) {
    this.url = url;
  }

  public String getUrl() {
    return this.url;
  }

  public static Environment custom(String url) {
    return new Environment(url);
  }
}
