/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.testinium.devicepark.core.util;

import java.util.Objects;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

/**
 * Helper (utility) methods for {@link Supplier}.
 *
 * <p>This class is an internal part of the SDK; applications depending on it
 * should not use it directly.</p>
 *
 * @since 1.0.0
 */
public final class Suppliers {
  private Suppliers() {
  }

  public static <T> Supplier<T> memoize(Supplier<T> delegate) {
    AtomicReference<T> value = new AtomicReference<>();
    return () ->  {
      T val = value.get();
      if (val == null) {
        val = value.updateAndGet(cur -> cur == null ? Objects.requireNonNull(delegate.get()) : cur);
      }
      return val;
    } ;
  }
}
