name: Publish to Maven Central

on:
  release:
    types: [published]

  push:
    branches:
      - TLT-3557

  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2

          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
            <servers>
              <server>
                <id>central</id>
                <username>${MAVEN_CENTRAL_USERNAME}</username>
                <password>${MAVEN_CENTRAL_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Verify
        run: mvn -B clean verify

      - name: Publish
        run: mvn -B -X deploy